name = "droitfpra"
compatibility_date = "2023-05-14"
main = "./functions/api/index.js"

# Specify the correct directory for the static export
[site]
bucket = "./out"

# Define the output directory for Pages deployment
pages_build_output_dir = "out"

[build]
command = "npm run build"

# Include static assets like headers and redirects
[site.static]
include = ["_headers", "_redirects"]

# Worker configuration
[env.production]
name = "droitfpra-api"
workers_dev = true
compatibility_date = "2023-05-14"
routes = ["droitfpra.pages.dev/api*"]

# Functions binding for Pages Functions
[env.production.functions_binding]
pages_app_binding = "PAGES_APP"

[env.production.build]
command = "npm run build"
output_directory = "out"

[[env.production.routes]]
pattern = "/*"
script = "" 